In [1]:
from zipfile import ZipFile
import warnings
warnings.filterwarnings('ignore')
import cv2
import os
import re
import numpy as np
import pandas as pd
from pandas import DataFrame,Series

#for feature extraction
from sklearn.preprocessing import normalize
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
# import seaborn as sns
%matplotlib inline
%pylab inline

#for basic models
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

Populating the interactive namespace from numpy and matplotlib


In [2]:
with ZipFile('fruits2.zip', 'r') as zipObj:
    listOfiles = zipObj.namelist()

In [3]:
listOfiles

['fruits2/Test/',
 'fruits2/Test/img10.jpg',
 'fruits2/Train/',
 'fruits2/Train/apple1.jpg',
 'fruits2/Train/apple10.jpg',
 'fruits2/Train/apple2.jpg',
 'fruits2/Train/apple3.jpg',
 'fruits2/Train/apple4.jpg',
 'fruits2/Train/apple5.jpg',
 'fruits2/Train/apple6.jpg',
 'fruits2/Train/apple7.jpg',
 'fruits2/Train/apple8.jpg',
 'fruits2/Train/apple9.jpg',
 'fruits2/Train/Banana1.jpg',
 'fruits2/Train/Banana10.jpg',
 'fruits2/Train/Banana2.jpg',
 'fruits2/Train/Banana3.jpg',
 'fruits2/Train/Banana4.jpg',
 'fruits2/Train/Banana5.jpg',
 'fruits2/Train/Banana6.jpg',
 'fruits2/Train/Banana7.jpg',
 'fruits2/Train/Banana8.jpg',
 'fruits2/Train/Banana9.jpg',
 'fruits2/Train/orange1.jpg',
 'fruits2/Train/orange10.jpg',
 'fruits2/Train/orange2.jpg',
 'fruits2/Train/orange3.jpg',
 'fruits2/Train/orange4.jpg',
 'fruits2/Train/orange5.jpg',
 'fruits2/Train/orange6.jpg',
 'fruits2/Train/orange7.jpg',
 'fruits2/Train/orange8.jpg',
 'fruits2/Train/orange9.jpg']

In [4]:
df = pd.DataFrame(listOfiles, columns = ['image path']) 

In [5]:
df

image path
0                fruits2/Test/
1       fruits2/Test/img10.jpg
2               fruits2/Train/
3     fruits2/Train/apple1.jpg
4    fruits2/Train/apple10.jpg
5     fruits2/Train/apple2.jpg
6     fruits2/Train/apple3.jpg
7     fruits2/Train/apple4.jpg
8     fruits2/Train/apple5.jpg
9     fruits2/Train/apple6.jpg
10    fruits2/Train/apple7.jpg
11    fruits2/Train/apple8.jpg
12    fruits2/Train/apple9.jpg
13   fruits2/Train/Banana1.jpg
14  fruits2/Train/Banana10.jpg
15   fruits2/Train/Banana2.jpg
16   fruits2/Train/Banana3.jpg
17   fruits2/Train/Banana4.jpg
18   fruits2/Train/Banana5.jpg
19   fruits2/Train/Banana6.jpg
20   fruits2/Train/Banana7.jpg
21   fruits2/Train/Banana8.jpg
22   fruits2/Train/Banana9.jpg
23   fruits2/Train/orange1.jpg
24  fruits2/Train/orange10.jpg
25   fruits2/Train/orange2.jpg
26   fruits2/Train/orange3.jpg
27   fruits2/Train/orange4.jpg
28   fruits2/Train/orange5.jpg
29   fruits2/Train/orange6.jpg
30   fruits2/Train/orange7.jpg
31   fruits2/Train/orange8.jpg
32   fruits2/Train/orange9.jpg

In [6]:
#separate into training and test sets
fruits_test = []
fruits_train = []

for mystring in df['image path']:
    if 'Test' in mystring: 
            fruits_test.append(mystring)

for mystring in df['image path']:
    if 'Train' in mystring: 
            fruits_train.append(mystring)
fruits_test = pd.DataFrame(fruits_test, columns = ['image path'])
fruits_train = pd.DataFrame(fruits_train, columns = ['image path'])

print(fruits_test)
print(fruits_train)


               image path
0           fruits2/Test/
1  fruits2/Test/img10.jpg
                    image path
0               fruits2/Train/
1     fruits2/Train/apple1.jpg
2    fruits2/Train/apple10.jpg
3     fruits2/Train/apple2.jpg
4     fruits2/Train/apple3.jpg
5     fruits2/Train/apple4.jpg
6     fruits2/Train/apple5.jpg
7     fruits2/Train/apple6.jpg
8     fruits2/Train/apple7.jpg
9     fruits2/Train/apple8.jpg
10    fruits2/Train/apple9.jpg
11   fruits2/Train/Banana1.jpg
12  fruits2/Train/Banana10.jpg
13   fruits2/Train/Banana2.jpg
14   fruits2/Train/Banana3.jpg
15   fruits2/Train/Banana4.jpg
16   fruits2/Train/Banana5.jpg
17   fruits2/Train/Banana6.jpg
18   fruits2/Train/Banana7.jpg
19   fruits2/Train/Banana8.jpg
20   fruits2/Train/Banana9.jpg
21   fruits2/Train/orange1.jpg
22  fruits2/Train/orange10.jpg
23   fruits2/Train/orange2.jpg
24   fruits2/Train/orange3.jpg
25   fruits2/Train/orange4.jpg
26   fruits2/Train/orange5.jpg
27   fruits2/Train/orange6.jpg
28   fruits2/Train/oran

In [7]:
fruits_train = fruits_train.drop(0)
fruits_test = fruits_test.drop(0)
fruits_test.shape

(1, 1)

In [8]:
res=[]
for i in range(10):
    res.append("apple")
for i in range(10):
    res.append("Banana")
for i in range(10):
    res.append("orange")
fruits_train['label'] = res
print(fruits_train)

res=[]
for i in range(1):
    res.append("test")
fruits_test['label'] = res
print(fruits_test)
# res = []
# for i in fruits_train['image path']:
#     res.append(re.findall("Train/(nt|[a-zA-Z\s+]+)", i)[0])
# fruits_train['label'] = res

# test_res = []
# for i in fruits_test['image path']:
#     test_res.append(re.findall("Test/(nt|[a-zA-Z\s+]+)", i)[0])
# fruits_test['label'] = test_res

                    image path   label
1     fruits2/Train/apple1.jpg   apple
2    fruits2/Train/apple10.jpg   apple
3     fruits2/Train/apple2.jpg   apple
4     fruits2/Train/apple3.jpg   apple
5     fruits2/Train/apple4.jpg   apple
6     fruits2/Train/apple5.jpg   apple
7     fruits2/Train/apple6.jpg   apple
8     fruits2/Train/apple7.jpg   apple
9     fruits2/Train/apple8.jpg   apple
10    fruits2/Train/apple9.jpg   apple
11   fruits2/Train/Banana1.jpg  Banana
12  fruits2/Train/Banana10.jpg  Banana
13   fruits2/Train/Banana2.jpg  Banana
14   fruits2/Train/Banana3.jpg  Banana
15   fruits2/Train/Banana4.jpg  Banana
16   fruits2/Train/Banana5.jpg  Banana
17   fruits2/Train/Banana6.jpg  Banana
18   fruits2/Train/Banana7.jpg  Banana
19   fruits2/Train/Banana8.jpg  Banana
20   fruits2/Train/Banana9.jpg  Banana
21   fruits2/Train/orange1.jpg  orange
22  fruits2/Train/orange10.jpg  orange
23   fruits2/Train/orange2.jpg  orange
24   fruits2/Train/orange3.jpg  orange
25   fruits2/Train/orange

In [9]:
fruit_images = []
labels = []

for i in range(1, len(fruits_train)):
    #read in image in color
    print(fruits_train['image path'][i])
    image = cv2.imread(fruits_train['image path'][i], cv2.IMREAD_COLOR)
    image = cv2.resize(image, (45, 45))
    #inverse image colors to show appropriately on screen (RGB to BGR)
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)    
    fruit_images.append(image)
    labels.append(fruits_train['label'][i])

#array of fruit images    
fruit_images = np.array(fruit_images)

#creating labels for images
labels = np.array(labels)
label2id = {v:i for i,v in enumerate(np.unique(labels))}
label_ids = np.array([label2id[x] for x in labels])

print(label_ids)


fruit_imagestest = []
for i in range(1, len(fruits_test)):
    #read in image in color
    print(fruits_test['image path'][i])
    image = cv2.imread(fruits_test['image path'][i], cv2.IMREAD_COLOR)
    image = cv2.resize(image, (45, 45))
    #inverse image colors to show appropriately on screen (RGB to BGR)
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)    
    fruit_imagestest.append(image)
    labels.append(fruits_test['label'][i])

#array of fruit images    
fruit_imagestest = np.array(fruit_images)
print(fruit_imagestest)



fruits2/Train/apple1.jpg
fruits2/Train/apple10.jpg
fruits2/Train/apple2.jpg
fruits2/Train/apple3.jpg
fruits2/Train/apple4.jpg
fruits2/Train/apple5.jpg
fruits2/Train/apple6.jpg
fruits2/Train/apple7.jpg
fruits2/Train/apple8.jpg
fruits2/Train/apple9.jpg
fruits2/Train/Banana1.jpg
fruits2/Train/Banana10.jpg
fruits2/Train/Banana2.jpg
fruits2/Train/Banana3.jpg
fruits2/Train/Banana4.jpg
fruits2/Train/Banana5.jpg
fruits2/Train/Banana6.jpg
fruits2/Train/Banana7.jpg
fruits2/Train/Banana8.jpg
fruits2/Train/Banana9.jpg
fruits2/Train/orange1.jpg
fruits2/Train/orange10.jpg
fruits2/Train/orange2.jpg
fruits2/Train/orange3.jpg
fruits2/Train/orange4.jpg
fruits2/Train/orange5.jpg
fruits2/Train/orange6.jpg
fruits2/Train/orange7.jpg
fruits2/Train/orange8.jpg
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2]
[[[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255

In [10]:
#scaling and default PCA on entire training set of images
scaler = StandardScaler()
images_scaled = scaler.fit_transform([i.flatten() for i in fruit_images])
pca = PCA().fit(images_scaled)

scaler = StandardScaler()
images_scaledtest = scaler.fit_transform([i.flatten() for i in fruit_imagestest])
pca_test = PCA().fit(images_scaledtest)


In [11]:
print(pca.explained_variance_ratio_)
explained_var = list(pca.explained_variance_ratio_)
shifted_var = explained_var
var_df = DataFrame()
var_df['explained_var'] = explained_var
var_df['shifted_var'] = shifted_var
var_df['shifted_var'] = var_df['shifted_var'].shift(-1)
var_df['shifted_var'].fillna(0)
var_df['difference'] = var_df['explained_var'] - var_df['shifted_var']

print(var_df['difference'])

v = var_df[var_df['difference'] < .001].reset_index()
v = v.rename(columns={'index': 'components'})
print(v.iloc[4])

[2.49915058e-01 1.31723249e-01 1.00944205e-01 7.00221872e-02
 5.77761635e-02 5.07014151e-02 3.91003823e-02 3.53924750e-02
 2.98859850e-02 2.44448755e-02 2.37351961e-02 2.07747929e-02
 2.02101081e-02 1.91404934e-02 1.69248705e-02 1.53708791e-02
 1.37705854e-02 1.32211596e-02 1.05864508e-02 8.86973768e-03
 8.33343528e-03 7.95590259e-03 6.94556476e-03 6.83349999e-03
 5.82849597e-03 5.16612399e-03 3.79881128e-03 2.62789675e-03
 4.92870548e-32]
0     0.118192
1     0.030779
2     0.030922
3     0.012246
4     0.007075
5     0.011601
6     0.003708
7     0.005506
8     0.005441
9     0.000710
10    0.002960
11    0.000565
12    0.001070
13    0.002216
14    0.001554
15    0.001600
16    0.000549
17    0.002635
18    0.001717
19    0.000536
20    0.000378
21    0.001010
22    0.000112
23    0.001005
24    0.000662
25    0.001367
26    0.001171
27    0.002628
28         NaN
Name: difference, dtype: float64
components       20.000000
explained_var     0.008333
shifted_var       0.007956
differe

In [12]:
pca = PCA(n_components=20)
pca_result = pca.fit_transform(images_scaled)

pca_test = PCA(n_components=1)
pca_result_test = pca.fit_transform(images_scaledtest)

In [13]:
pcadf = DataFrame()
for i in range(20):
    pcadf[i] = pca_result[:,i]
pcadf.head()

0          1          2          3          4          5   \
0  21.313123 -17.435969  -5.143303  43.015250 -35.109493  -7.174970   
1 -10.024925 -17.965861  19.750809 -12.037943 -17.694516   9.402342   
2 -29.850361 -10.533761   1.060519 -20.220541   8.361859  -0.099965   
3  -7.630634 -22.790412  25.752713  -6.095997  10.446529 -17.137539   
4 -26.557830   1.982291  -8.534548 -34.147572   4.343289   5.751382   

          6         7          8          9          10         11         12  \
0 -19.841879 -0.682161 -14.032821 -27.890659   6.676557   3.983008  17.773413   
1   7.666287  2.492485  -9.931919  -6.650495  -6.113094   3.521765   1.503591   
2  -3.152465 -9.395090   1.176148  11.644089  16.687870   6.657435  -2.293743   
3  -9.139026 -4.592990  17.354649   5.263691  28.906498 -15.675558  -1.538680   
4  -5.478779 -7.358962 -12.793540  10.829003  18.106229   8.965748   3.305794   

          13         14         15         16         17        18         19  
0   7.577677  10.977992 -19.524266  -0.749195 -10.283265 -0.443186   1.225975  
1  -6.426980  -9.143645   2.599256  -1.850021  -5.890171  4.591219 -14.519496  
2   3.200274   9.490812   0.943716  -5.307527  -9.106795 -0.599040  -0.382046  
3  22.511962 -14.145281 -16.713132   3.671811  13.669599 -0.834440  -2.627224  
4  11.805746   6.702597  -1.705578 -12.487191  -7.005953  1.095587  -4.100824

In [14]:
X_train, X_test, y_train, y_test = train_test_split(pcadf, label_ids, test_size=0.20, random_state=42)
#X_train = pcadf
#y_train = label_ids
#X_test = pca_result_test


In [15]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
#print(X_test.shape[0], (y_test != y_pred).sum())

In [16]:
#X_test.shape

In [17]:
y_pred

array([1, 0, 0, 1, 1, 1])

In [18]:
y_pred-y_test

array([-1,  0,  0, -1,  0,  0])

In [19]:
y_test

array([2, 0, 0, 2, 1, 1])

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.6666666666666666